AWSTemplateFormatVersion: "2010-09-09"
Description: "hambach API."
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  VaultToken:
    Type: "String"
    Default: "default"
  READKEY:
    Type: "String"
  WRITEKEY:
    Type: "String"

Globals:
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
      AllowOrigin: "'*'"


Resources:
  content:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub "content"
      Timeout: 10
      Runtime: "provided.al2"
      Architectures:
        - x86_64
      Environment:
        Variables:
          READ_KEY: !Ref READKEY
      Events:
        ApiEvent:
          Type: "HttpApi"
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/content"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/content/{id}"
            Method: "get"

  article:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub "article"
      Timeout: 10
      Runtime: "provided.al2"
      Architectures:
        - x86_64
      Environment:
        Variables:
          READ_KEY: !Ref READKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/article"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/article/{id}"
            Method: "get"

  contentPut:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub "contentPut"
      Timeout: 10
      Runtime: "provided.al2"
      Architectures:
        - x86_64
      Environment:
        Variables:
          WRITE_KEY: !Ref WRITEKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/content"
            Method: "put"

  files:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub "files"
      Timeout: 10
      Runtime: "provided.al2"
      Architectures:
        - x86_64
      Environment:
        Variables:
          READ_KEY: !Ref READKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/files"
            Method: "get"
      
  filePost:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub "filePost"
      Timeout: 10
      Runtime: "provided.al2"
      Architectures:
        - x86_64
      Environment:
        Variables:
          WRITE_KEY: !Ref WRITEKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/files"
            Method: "post"

  fileDelete:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub "filesDelete"
      Timeout: 10
      Runtime: "provided.al2"
      Architectures:
        - x86_64
      Environment:
        Variables:
          WRITE_KEY: !Ref WRITEKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/files/{id}"
            Method: "delete"
